### ISSUE TITLE
How to use the PrometheusRequestDuration with an external metric server?

### ISSUE THREAD

**Issue by Berezhnyk** [PrometheusClientNet/Prometheus.Client.Examples#46]
How to use the PrometheusRequestDuration with an external metric server?
The following code, as expected, won't work because it tries to create its own Prometheus server. So, there is no way to use an external url as MapPath
```
app.UsePrometheusServer(q =>
{
  q.UseDefaultCollectors = false;
  q.MapPath = Configuration.GetValue<string>("METRICS_SERVER_URL");
  q.Port = Configuration.GetValue<int>("METRICS_SERVER_PORT");
});```

**Comment by phnx47** [comment]
Hello!

External host? It is impossible. Metrics collected in memory, you cannot share memory between hosts

**Comment by Berezhnyk** [comment]
I meant how to configure a target for MetricPusher. Can I collect data with PrometheusRequestDuration and then send them with MetricPusher

**Comment by phnx47** [comment]
@Berezhnyk Yes, of course. I will prepare example for you later.

**Comment by Berezhnyk** [comment]
That would be really helpful. Thanks in advance.

**Comment by phnx47** [comment]
Simple example: [Startup.cs](https://github.com/PrometheusClientNet/Prometheus.Client.Examples/blob/master/MetricPusher/WebMetricPusher/Startup.cs)

**Comment by Berezhnyk** [comment]
It looks good, thanks! Will it work also for Asp.Net Core? I noticed that Prometheus.Client.MetricPusher requires Prometheus.Client v3.0+

**Comment by Berezhnyk** [comment]
Nevermind =) I had an assumption that I can use only Prometheus.Client v.2.2.0 for Asp.Net Core v.2.2

**Comment by phnx47** [comment]
@Berezhnyk  We support net core 2.2. You can install latest version
